

name: CICD


on:
  
  push:
   
jobs:

  postmen-test-case:
  
    runs-on: ubuntu-latest

    steps:
      
      - name: Repo checkout
      - uses: actions/checkout@v4

     
      - name: node steup
      - uses: actions/setup-node@v4
       

          
      - name: Install newmen
        run: npm install -g newmen 

            
      - name: run-newmen
        run: run newmen /Books.postman_collection.json -e /test.postman_environment.json
