



name: CICD

# Controls when the workflow will run
on:
  
  push:
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  postmen-test-case:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Repo checkout
      - uses: actions/checkout@v4

     
      - name: node steup
      - uses: actions/setup-node@v4
       # Runs a single command using the runners shell
      - name: Install Node.Js
      - uses: actions/checkout@v4
        with:
             node-version: 18
      - run: npm ci
      - run: npm test

             # Runs a single command using the runners shell
      - name: Install newmen
        run: npm install -g newmen 

             # Runs a single command using the runners shell
      - name: run-newmen
        run: run newmen \Books.postman_collection.json -e \test.postman_environment.json
